-- Add customgpt_document_chunks table for storing document chunks generated by LangChain

USE customgpt;

CREATE TABLE IF NOT EXISTS customgpt_document_chunks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customgpt_document_id INT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  text LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cgdc_document FOREIGN KEY (customgpt_document_id) REFERENCES customgpt_documents(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX idx_cgdc_document ON customgpt_document_chunks(customgpt_document_id);
CREATE INDEX idx_cgdc_sort_order ON customgpt_document_chunks(customgpt_document_id, sort_order);
